#%RAML 1.0 Trait
usage: A trait to use for all methods
queryParameters:
  correlationId:
    description: "Sending application defined and used for asynch api's"
    type: string
    required: false
  clientApplication:
    description: "Name of the sending application"
    type: string
    required: false