#%RAML 1.0 Trait
usage: A trait to use for International Categories and Product Lookup
queryParameters:
        storeId:
          description: storeId
          default: EU
          type: string
          enum: ["UK", "IE","EU"]